init:
  - git config --global core.autocrlf true

environment:
  matrix:
  - nodejs_version: 4
  - nodejs_version: 6
  - nodejs_version: 7

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version x64
  - ps: >-
      if ($env:nodejs_version -eq "4") {
        npm -g install npm@3
        $env:PATH="$env:APPDATA\npm;$env:PATH"
      }
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  # run tests
  - npm test

# Don't actually build.
build: off

matrix:
  fast_finish: true
